=== biocompute-objects/BCO_Documentation/ieee-2791-schema/2791object.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://w3id.org/ieee/ieee-2791-schema/2791object.json",
    "type": "object",
    "title": "Base type for all IEEE-2791 Objects",
    "description": "All IEEE-2791 object types must adhear to this type in order to be compliant with IEEE-2791 standard",
    "required": [
        "object_id",
        "spec_version",
        "etag",
        "provenance_domain",
        "usability_domain",
        "description_domain",
        "execution_domain",
        "io_domain"
    ],
    "definitions": {
        "object_id": {
            "type": "string",
            "description": "A unique identifier that should be applied to each IEEE-2791 Object instance, generated and assigned by a IEEE-2791 database engine. IDs should never be reused"
        },
        "uri": {
            "type": "object",
            "description": "Any of the four Resource Identifers defined at https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-7.3.5",
            "additionalProperties": false,
            "required": [
                "uri"
            ],
            "properties": {
                "filename": {
                    "type": "string"
                },
                "uri": {
                    "type": "string",
                    "format": "uri"
                },
                "access_time": {
                    "type": "string",
                    "description": "Time stamp of when the request for this data was submitted",
                    "format": "date-time"
                },
                "sha1_checksum": {
                    "type": "string",
                    "description": "output of hash function that produces a message digest",
                    "pattern": "[A-Za-z0-9]+"
                }
            }
        }, 
        "contributor": {
            "type": "object",
            "description": "Contributor identifier and type of contribution (determined according to PAV ontology) is required",
            "required": [
                "contribution",
                "name"
            ],
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of contributor",
                    "examples": [
                        "Charles Darwin"
                    ]
                },
                "affiliation": {
                    "type": "string",
                    "description": "Organization the particular contributor is affiliated with",
                    "examples": [
                        "HMS Beagle"
                    ]
                },
                "email": {
                    "type": "string",
                    "description": "electronic means for identification and communication purposes",
                    "examples": [
                        "name@example.edu"
                    ],
                    "format": "email"
                },
                "contribution": {
                    "type": "array",
                    "description": "type of contribution determined according to PAV ontology",
                    "reference": "https://doi.org/10.1186/2041-1480-4-37",
                    "items": {
                        "type": "string",
                        "enum": [
                            "authoredBy",
                            "contributedBy",
                            "createdAt",
                            "createdBy",
                            "createdWith",
                            "curatedBy",
                            "derivedFrom",
                            "importedBy",
                            "importedFrom",
                            "providedBy",
                            "retrievedBy",
                            "retrievedFrom",
                            "sourceAccessedBy"
                        ]
                    }
                },
                "orcid": {
                    "type": "string",
                    "description": "Field to record author information. ORCID identifiers allow for the author to curate their information after submission. ORCID identifiers must be valid and must have the prefix ‘https://orcid.org/’",
                    "examples": [
                        "http://orcid.org/0000-0002-1825-0097"
                    ],
                    "format": "uri"
                }
            }
        }
    },
    "additionalProperties": false,
    "properties": {
        "object_id": {
            "$ref": "#/definitions/object_id",
            "readOnly": true
        },
        "spec_version": {
            "type": "string",
            "description": "Version of the IEEE-2791 specification used to define this document",
            "examples": [
                "https://w3id.org/ieee/ieee-2791-schema/"
            ],
            "readOnly": true,
            "format": "uri"
        },
        "etag": {
            "type": "string",
            "description": "See https://tools.ietf.org/html/rfc7232#section-2.1 for full description. It is recommended that the ETag be deleted or updated if the object file is changed (except in cases using weak ETags in which the entirety of the change comprises a simple re-writing of the JSON).",
            "examples": [
                "5986B05969341343E77A95B4023600FC8FEF48B7E79F355E58B0B404A4F50995"
            ],
            "readOnly": true,
            "pattern": "^([A-Za-z0-9]+)$"
        },
        "provenance_domain": {
            "$ref": "provenance_domain.json"
        },
        "usability_domain": {
            "$ref": "usability_domain.json"
        },
        "extension_domain": {
            "type": "array",
            "description": "An optional domain that contains user-defined fields.",
            "items":{
                "required":[
                    "extension_schema"
                ],
                "additionalProperties": true,
                "properties": {
                    "extension_schema":{
                        "title": "Extension Schema",
                        "description": "resolving this URI should provide this extension's JSON Schema",
                        "type": "string",
                        "format": "uri"
                    }
                }
            }
        },
        "description_domain": {
            "$ref": "description_domain.json"
        },
        "execution_domain": {
            "$ref": "execution_domain.json"
        },
        "parametric_domain": {
            "$ref": "parametric_domain.json"
        },
        "io_domain": {
            "$ref": "io_domain.json"
        },
        "error_domain": {
            "$ref": "error_domain.json"
        }
    }
}

=== biocompute-objects/BCO_Documentation/content/examples/UVP.json
{
    "object_id": "https://w3id.org/biocompute/1.3.0/examples/UVP_BCO.json",
    "etag": "39fb1c62f43ff72ac95f91a433d5e425fb08bc07ec0f719ecfd27fb3cd3a3635",
    "spec_version": "https://w3id.org/biocompute/1.3.0/",
    "provenance_domain": {
        "name": "Lineage assignment for an isolate of M. tuberculosis based on its single nucleotide polymorphism (SNP) profile based on UVC v1.0.",
        "version": "v1.0",
        "review": [
            {
                "status": "approved",
                "reviewer_comment": "Approved by GW staff.",
                "date": "2017-11-12T12:30:48-0400",
                "reviewer": {
                    "name": "Anjan Purkayastha",
                    "affiliation": "George Washington University",
                    "email": "anjan.purkayastha@gmail.com",
                    "contribution": [
                        "curatedBy"
                    ]
                }
            },
            {
                "status": "approved",
                "reviewer_comment": "Approved by Critical Path Institute staff.",
                "date": "2017-11-12T12:30:48-0400",
                "reviewer": {
                    "name": "Marco Schito",
                    "affiliation": "Critical Path Institute",
                    "email": "mschito@c-path.org",
                    "contribution": [
                        "curatedBy"
                    ]
                }
            },
            {
                "status": "approved",
                "date": "2017-11-12T12:30:48-0400",
                "reviewer_comment": "Approved by Critical Path Institute staff.",
                "reviewer": {
                    "name": "Kenneth Ramey",
                    "affiliation": "Critical Path Institute",
                    "email": "kramey@c-path.org",
                    "contribution": [
                        "curatedBy"
                    ]
                }
            }
        ],
        "obsolete_after": "2118-09-26T14:43:43-0400",
        "embargo": {
            "start_time": "2000-09-26T14:43:43-0400",
            "end_time": "2018-10-08T18:02:33-0400"
        },
        "created": "2017-11-12T12:30:48-0400",
        "modified": "2018-10-08T18:35:33-0400",
        "contributors": [
            {
                "name": "Matthew Ezewudo",
                "affiliation": "Critical Path Institute",
                "email": "mezewudo@c-path.org",
                "contribution": [
                    "authoredBy"
                ]
            },
            {
                "name": "Jamie Posie",
                "affiliation": "CDC Atlanta, GA",
                "contribution": [
                    "authoredBy"
                ]
            },
            {
                "name": "Anjan Purkayastha",
                "affiliation": "George Washington University",
                "email": "anjan.purkayastha@gmail.com",
                "contribution": [
                    "authoredBy",
                    "curatedBy"
                ]
            },
            {
                "name": "Marco Schito",
                "affiliation": "Critical Path Institute",
                "email": "mschito@c-path.org",
                "contribution": [
                    "authoredBy"
                ]
            },
            {
                "name": "Charles Hadley King",
                "affiliation": "George Washington University",
                "email": "hadley_king@gwu.edu",
                "contribution": [
                    "authoredBy",
                    "curatedBy"
                ],
                "orcid": "https://orcid.org/0000-0003-1409-4549"
            },
            {
                "name": "ReseqTB Consortium",
                "affiliation": "Critical Path Institute",
                "email": "info@c-path.org",
                "contribution": [
                    "createdAt"
                ]
            }
        ],
        "license": "https://spdx.org/licenses/CC-BY-4.0.html"
    },
    "usability_domain": [
        "Lineage assignment for an isolate of M. tuberculosis[taxonomy:1773] based on its single nucleotide polymorphism [so:0000694] (SNP) profile."
    ],
    "extension_domain": [
        {
            "extension_schema": "https://raw.githubusercontent.com/biocompute-objects/extension_domain/1.1.0/scm/scm_extension.json",
            "scm_extension": {
                "scm_repository": "https://github.com/CPTR-ReSeqTB/UVP",
                "scm_type": "git",
                "scm_commit": "9e8f588b3cd3f5eebde29f7d2879e1a1e1c1aed3",
                "scm_path": "UVP/scripts/UVP.py"
            }
        }
    ],
    "description_domain": {
        "keywords": [
            "Mycobacterium tuberculosis",
            "Phylogenetics",
            "Bacterial lineage analysis",
            "Single Nucleotide Polymorphism",
            "SNP"
        ],
        "xref": [
            {
                "namespace": "pubmed",
                "name": "PubMed",
                "ids": [
                    "00000"
                ],
                "access_time": "2018-13-02T10:15-05:00"
            },
            {
                "namespace": "so",
                "name": "Sequence Ontology",
                "ids": [
                    "0000694"
                ],
                "access_time": "2018-13-02T10:15-05:00"
            },
            {
                "namespace": "taxonomy",
                "name": "Taxonomy",
                "ids": [
                    "1773"
                ],
                "access_time": "2018-13-02T10:15-05:00"
            }
        ],
        "platform": [
            "Linux"
        ],
        "pipeline_steps": [
            {
                "step_number": 1,
                "name": "FastQValidator",
                "description": "To verify if input file is in fastq format",
                "version": "1.0.5",
                "input_list": [
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_input_fastq_files/ERR552106_1.fastq.gz"
                    },
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_input_fastq_files/ERR552106_2.fastq.gz"
                    }
                ],
                "output_list": [
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_results/ERR552106/validation/Validation_report.txt"
                    }
                ]
            },
            {
                "step_number": 2,
                "name": "FastQC",
                "description": "assess Quality of raw sequence reads",
                "version": "0.11.5",
                "input_list": [
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_input_fastq_files/ERR552106_1.fastq.gz"
                    },
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_input_fastq_files/ERR552106_2.fastq.gz"
                    }
                ],
                "output_list": [
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_results/ERR552106/fastqc/ERR552106_1_fastqc.html"
                    },
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_results/ERR552106/fastqc/ERR552106_1_fastqc.zip"
                    },
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_results/ERR552106/fastqc/ERR552106_2_fastqc.html"
                    },
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_results/ERR552106/fastqc/ERR552106_2_fastqc.zip"
                    }
                ]
            },
            {
                "step_number": 3,
                "name": "Kraken",
                "description": "Assesses species specificity of sequence reads",
                "version": "0.10.5",
                "input_list": [
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_input_fastq_files/ERR552106_1.fastq.gz"
                    },
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_input_fastq_files/ERR552106_2.fastq.gz"
                    }
                ],
                "output_list": [
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_results/ERR552106/kraken/final_report.txt"
                    }
                ]
            },
            {
                "step_number": 4,
                "name": "BWA",
                "description": "Aligns sequence reads to reference genome",
                "version": "0.7.12",
                "prerequisite": [
                    {
                        "name": "M. tuberculosis H37Rv genome reference file",
                        "uri": {
                            "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_reference_files/NC_000962.fa"
                        }
                    }
                ],
                "input_list": [
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_input_fastq_files/ERR552106_1.fastq.gz"
                    },
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_input_fastq_files/ERR552106_2.fastq.gz"
                    }
                ],
                "output_list": [
                    {
                        "uri": "http://bco.reseqtb.org/UVP-BCO/UVPv2.4.1_sample_results/ERR552106/bam_files/ERR552106.bam"
                    }
                ]
            },
            {
                "step_number": 5,
                "name": "Qualimap",
                "description": "Assess mapping quality of aligned reads",
