=== biocompute-objects/BCO_Documentation/schema.v1.0/infered.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://example.com/root.json",
	"type": "object",
	"title": "BioCompute Schema",
	"definitions": {
	},
	"required": [
		"id",
		"name",
		"version",
		"createdby",
		"created",
		"modified",
		"digital_signature",
		"verification_status",
		"publication_status",
		"usability_domain",
		"authors",
		"description_domain",
		"execution_domain",
		"parametric_domain",
		"io_domain"
	],
	"properties": {
		"id": {
			"type": "string",
			"title": "ID",
			"examples": [
				"obj.1283"
			],
			"pattern": "^(.*)$"
		},
		"name": {
			"type": "string",
			"title": "Name",
			"examples": [
				"Quasispecies analysis of HIV-1 [taxID:12721] samples taken from H1V-1 infected individuals [taxID:9606] and detection of novel HIV-1 recombinant subtypes"
			],
			"pattern": "^(.*)$"
		},
		"structured_name": {
			"type": "string",
			"title": "Structured Name",
			"default": "",
			"examples": [
				"Quasispecies analysis of HIV-1"
			],
			"pattern": "^(.*)$"
		},
		"version": {
			"type": "string",
			"title": "Version",
			"default": "1.0",
			"examples": [
				"1.0"
			],
			"pattern": "^(.*)$"
		},
		"digital_signature": {
			"type": "string",
			"title": "Digital Signature",
			"examples": [
				"324kjhgiufgioerfhlsjdhbfalskjd"
			],
			"pattern": "^(.*)$"
		},
		"verification_status": {
			"type": "string",
			"title": "Verification Status",
			"default": "unreviewed",
			"examples": [
				"in_progress",
				"unreviewed",
				"reviewed",
				"published",
				"rejected"
			],
			"pattern": "^(.*)$"
		},
		"publication_status": {
			"type": "string",
			"title": "Publication Status",
			"default": "draft",
			"examples": [
				"draft",
				"in_progress",
				"private",
				"open_access"
			],
			"pattern": "^(.*)$"
		},
		"authors": {
			"type": "array",
			"title": "Authors",
			"items": {
				"type": "object",
				"properties": {
					"orcid": {
						"type": "string",
						"title": "Open Researcher and Contributor ID",
						"examples": [
							"https://orcid.org/0000-0003-1409-4549"
						],
						"pattern": "^(.*)$"
					},
					"name": {
						"type": "string",
						"title": "Name",
						"examples": [
							"John Doe"
						],
						"pattern": "^(.*)$"
					}
				},
				"additionalProperties": false
			}
		},
		"usability_domain": {
			"type": "array",
			"title": "Usability Domain",
			"items": {
				"type": "string",
				"examples": [
					"This pipeline can be used for discovering the new recombinant subtypes of viruses"
				],
				"pattern": "^(.*)$"
			}
		},
		"createdby": {
			"type": "string",
			"title": "Created By",
			"examples": [
				"darwin@gwu.edu"
			],
			"pattern": "^(.*)$"
		},
		"created": {
			"type": "string",
			"title": "Created",
			"examples": [
				"Feb 02, 2017 14:37:50"
			],
			"pattern": "^(.*)$"
		},
		"modified": {
			"type": "string",
			"title": "Modified",
			"examples": [
				"Jun 16, 2017 15:04:43"
			],
			"pattern": "^(.*)$"
		},
		"description_domain": {
			"type": "object",
			"title": "Description Domain",
			"required": [
				"keywords",
				"xref",
				"pipeline_steps"
			],
			"properties": {
				"keywords": {
					"type": "array",
					"title": "Keywords",
					"items": {
						"type": "string",
						"examples": [
							"clonal discovery",
							"quasispecies",
							"clonal contigs",
							"HIV-1"
						],
						"pattern": "^(.*)$"
					}
				},
				"xref": {
					"type": "array",
					"title": "External References",
					"items": {
						"type": "string",
						"examples": [
							"UBERON:0001969",
							"taxID:9606",
							"taxID:12721"
						],
						"pattern": "^(.*)$"
					}
				},
				"pipeline_steps": {
					"type": "array",
					"title": "Pipeline Steps",
					"items": {
						"type": "object",
						"required": [
							"tool_name",
							"tool_desc",
							"tool_version",
							"tool_package",
							"step_number",
							"input_uri_list",
							"output_uri_list"
						],
						"properties": {
							"tool_name": {
								"type": "string",
								"title": "Tool Name",
								"examples": [
									"HIVE-hexagon"
								],
								"pattern": "^(.*)$"
							},
							"tool_desc": {
								"type": "string",
								"title": "Tool Description",
								"examples": [
									"Aligns reads to a set of reference"
								],
								"pattern": "^(.*)$"
							},
							"tool_version": {
								"type": "string",
								"title": "Tool Version",
								"examples": [
									"1.4.3"
								],
								"pattern": "^(.*)$"
							},
							"tool_package": {
								"type": "string",
								"title": "Tool Requirements",
								"examples": [
									"HIVE"
								],
								"pattern": "^(.*)$"
							},
							"step_number": {
								"type": "string",
								"title": "Step Number",
								"examples": [
									"1"
								],
								"pattern": "^(.*)$"
							},
							"input_uri_list": {
								"type": "array",
								"title": "Input URI List",
								"items": {
									"type": "string",
									"examples": [
										"https://hive/data/nuc-read/645175"
									],
									"pattern": "^(.*)$"
								}
							},
							"output_uri_list": {
								"type": "array",
								"title": "Output URI List",
								"items": {
									"type": "string",
									"examples": [
										"https://hive/data/hitlist/557006.csv"
									],
									"pattern": "^(.*)$"
								}
							}
						}
					}
				}
			}
		},
		"execution_domain": {
			"type": "object",
			"title": "Execution Domain",
			"required": [
				"script",
				"pipeline_version",
				"platform",
				"driver",
				"software_prerequisites",
				"domain_prerequisites",
				"env_parameters",
				"script_type"
			],
			"properties": {
				"script": {
					"type": "string",
					"title": "Script",
					"examples": [
						"hive://workflows/quasispecies_analysis_of_HIV-1_viruses_hive.py"
					],
					"pattern": "^(.*)$"
				},
				"pipeline_version": {
					"type": "string",
					"title": "Pipeline Version",
					"examples": [
						"1.0"
					],
					"pattern": "^(.*)$"
				},
				"platform": {
					"type": "string",
					"title": "Platform",
					"examples": [
						"HIVE"
					],
					"pattern": "^(.*)$"
				},
				"driver": {
					"type": "string",
					"title": "The Driver Schema",
					"examples": [
						"//hive.biochemistry.gwu.edu/hive-driver"
					],
					"pattern": "^(.*)$"
				},
				"software_prerequisites": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string",
								"pattern": "^(.*)$"
							},
							"version": {
								"type": "string",
								"pattern": "^(.*)$"
							}
						}
					}
				},
				"domain_prerequisites": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"url": {
								"type": "string",
								"pattern": "^(.*)$"
							},
							"name": {
								"type": "string",
								"pattern": "^(.*)$"
							}
						}
					}
				},
				"env_parameters": {
					"type": "array",
					"title": "Environment Parameters",
					"items": {
						"type": "string",
						"examples": [
							"HIVEv1.4.3"
						],
						"pattern": "^(.*)$"
					}
				},
				"script_type": {
					"type": "string",
					"title": "Script Type",
					"examples": [
						"URI"
					],
					"pattern": "^(.*)$"
				}
			}
		},
		"parametric_domain": {
			"type": "object",
			"title": "Parametric Domain"
		},
		"io_domain": {
			"$id": "#/properties/io_domain",
			"type": "object",
			"title": "The Io_domain Schema",
			"required": [
				"input_uri_list",
				"output_uri_list"
			],
			"properties": {
				"reference_uri_list": {
					"type": "array",
					"title": "Reference URI List",
					"items": {
						"type": "string",
						"examples": [
							"hive://genomes/333333"
						],
						"pattern": "^(.*)$"
					}
				},
				"input_uri_list": {
					"type": "array",
					"title": "Input URI List",
					"items": {
						"type": "string",
						"examples": [
							"hive://genomes/333333"
						],
						"pattern": "^(.*)$"
					}
				},
				"output_uri_list": {
					"type": "array",
					"title": "Output URI List",
					"items": {
						"type": "string",
						"examples": [
							"hive://data/888888/popSummary"
						],
						"pattern": "^(.*)$"
					}
				}
			}
		}
	}
}

=== biocompute-objects/BCO_Documentation/2_Gut/bcoexample_2.json
{
	"id": "obj.1276",
	"name": "Healthy human [taxID:9606] fecal [UBERON:0001988] metagenomic diversity",
	"structured_name": "Healthy human [taxID:9606] fecal [UBERON:0001988] metagenomic diversity",
	"version": "1.2",
	"createdby": "hadley_king@gwmail.gwu.edu",
	"created": "Jan 26, 2017 16:35:29",
	"modified": "May 11, 2017 11:43:42",
	"digital_signature": "QSEQa6HNzERVIMONZWEj",
	"verification_status": "unreviewed",
	"publication_status": "draft",
	"usability_domain": [
		"Identify the most common organism present in a human [taxID:9606] fecal [UBERON:0001988] sample, ",
		"Identify the general community composition of organisms in a human [taxID:9606] fecal [UBERON:0001988] sample, ",
		"CensuScope is used to do a census of the composition of the read files. Based on a user-defined threshold, organisms identified are used for alignment in the Hexagon alignment."
	],
	"authors": [
		{
			"orcid": "0000-0003-1409-4549"
		},
		{
			"orcid": "0000-0002-8138-8312"
		}
	],
	"description_domain": {
		"keywords": [
			"metagenome",
			"metagenomic analysis",
			"fecal"
		],
		"xref": [
			"UBERON:0001988",
			"taxID:9606"
		],
		"pipeline_steps": [
			{
				"tool_name": "HIVE_CensuScope",
				"tool_desc": "Detect taxonomic composition of a metagenomic data set.",
				"tool_version": "1.3",
				"tool_package": "null",
				"step_number": "1",
				"input_uri_list": [
					"hive://nuc-read/514683",
					"hive://nuc-read/514682",
					"hive://genome/513957"
				],
				"output_uri_list": [
					"hive:///data/524669/dnaAccessionBasedResult.csv"
				]
			},
			{
				"tool_name": "HIVE_hexagon",
				"tool_desc": "Alignment of reads to a set of references",
				"tool_version": "1.3",
				"tool_package": "null",
				"step_number": "2",
				"input_uri_list": [
					"https://www.ncbi.nlm.nih.gov/nuccore/CP000139.1",
					"https://www.ncbi.nlm.nih.gov/nuccore/FP929042.1",
					"https://www.ncbi.nlm.nih.gov/nuccore/FP929046.1",
					"https://www.ncbi.nlm.nih.gov/nuccore/FP929045.1",
					"https://www.ncbi.nlm.nih.gov/nuccore/FP929043.1",
					"https://www.ncbi.nlm.nih.gov/nuccore/FP929048.1",
					"hive:///data/524669/dnaAccessionBasedResult.csv"
				],
				"output_uri_list": [
					"hive://data/524569/alCount-Unalignedo524569-alCount--1.csv"
				]
			}
		]
	},
	"execution_domain": {
		"script": "hive://workflows/human_gut_metagenomic_diversity.py",
		"pipeline_version": "2.0",
		"platform": "HIVE",
		"driver": "python_v2.7.13",
		"software_prerequisites": [
			{
				"name": "HIVE_censuscope",
				"version": "1.3"
			},
			{
				"name": "HIVE_hexagon",
				"version": "1.3"
			}
		],
		"domain_prerequisites": [
			{
				"url": "protocol://domain:port/application/path",
				"name": "generic name"
			},
			{
				"url": "ftp://:22/",
				"name": "access to ftp"
			}
		],
		"env_parameters": [
			"HIVEv1.3"
		],
		"script_type": "URI"
	},
	"parametric_domain": {
		"complexityRefEntropy": "1.2 - reluctant",
		"maximumPercentLowQualityAllowed": "15",
		"keepMarkovnikovMatches": "On",
		"storeAlignments": "Yes",
		"keepAllMatches": "All equally best alternative matches",
		"selfStopping": "No",
		"CensuslimitIterations": "5",
		"sample": "2500",
		"acceptNNNQuaTrheshold": "filter Ns only",
		"complexityRefWindow": "30",
		"taxDepth": "leaf",
		"minMatchLen": "45"
	},
	"io_domain": {
		"reference_uri_list": [
			"https://www.ncbi.nlm.nih.gov/nuccore/CP000139.1",
			"https://www.ncbi.nlm.nih.gov/nuccore/FP929042.1",
			"https://www.ncbi.nlm.nih.gov/nuccore/FP929046.1",
			"https://www.ncbi.nlm.nih.gov/nuccore/FP929045.1",
			"https://www.ncbi.nlm.nih.gov/nuccore/FP929043.1",
			"https://www.ncbi.nlm.nih.gov/nuccore/FP929048.1",
			"hive://genome/513957"
		],
		"input_uri_list": [
			"https://hive.biochemistry.gwu.edu/nuc-read/514683",
			"https://hive.biochemistry.gwu.edu/nuc-read/514682"
		],
		"output_uri_list": [
			"https://hive.biochemistry.gwu.edu/data/524669/dnaAccessionBasedResult.csv",
			"https://hive.biochemistry.gwu.edu/data/524569/Unaligned Reads (HIVE_ID).fasta",
			"https://hive.biochemistry.gwu.edu/data/524569/alCount-Unalignedo524569-alCount--1.csv"
		]
	}
}

=== biocompute-objects/BCO_Documentation/6_clonalDisc/bcoexample_6.json
{
	"id": "obj.1283",
	"name": "Quasispecies analysis of HIV-1 [taxID:12721] samples taken from H1V-1 infected individuals [taxID:9606] and detection of novel HIV-1 recombinant subtypes",
	"structured_name": "Quasispecies analysis of HIV-1",
	"version": "1.0",
	"createdby": "naila_gulzar@gwu.edu",
	"created": "Feb 02, 2017 14:37:50",
	"modified": "Jun 16, 2017 15:04:43",
	"digital_signature": "324kjhgiufgioerfhlsjdhbfalskjd",
	"verification_status": "unreviewed",
	"publication_status": "draft",
	"usability_domain": [
		"This pipeline can be used for discovering the new recombinant subtypes of viruses"
	],
	"authors": [
		{
			"orcid": "0000-0002-8138-8312"
		},
		{
			"name": "Bhavna Hora"
		},
		{
			"name": "Konstantinos Karagiannis "
		},
		{
			"name": "Krista Smith"
		},
		{
			"name": "Raja Mazumder"
		},
		{
			"name": "Feng Gao"
		}
	],
	"description_domain": {
		"keywords": [
			"clonal discovery",
			"quasispecies",
			"clonal contigs",
			"HIV-1"
		],
		"xref": [
			"UBERON:0001969",
			"taxID:9606",
			"taxID:12721"
		],
		"pipeline_steps": [
			{
				"tool_name": "HIVE-hexagon",
				"tool_desc": "Aligns reads to a set of reference",
				"tool_version": "1.4.3",
				"tool_package": "HIVE",
				"step_number": "1",
				"input_uri_list": [
					"https://hive/data/nuc-read/645175",
					"https://hive/data/nuc-read/645176",
					"https://hive/data/nuc-genome/545173"
				],
				"output_uri_list": [
					"https://hive/data/hitlist/557006.csv"
				]
			},
			{
				"tool_name": "HIve-seq",
				"tool_desc": "Utility set that allows sequence manipulation",
				"tool_version": "1.4.3",
				"tool_package": "HIVE",
				"step_number": "2",
				"input_uri_list": [
					"https://hive/data/hitlist/557006.csv"
				],
				"output_uri_list": [
					"https://hive/data/seqtrim/557007.fasta"
				]
			},
			{
				"tool_name": "HIVE-MAFFT",
				"tool_desc": "Multiple sequence alignment tool",
				"tool_version": "1.4.3",
				"tool_package": "HIVE",
				"step_number": "3",
				"input_uri_list": [
					"https://hive/data/seqtrim/557007.fasta"
				],
				"output_uri_list": [
					"https://hive/data/MAFFT/557008.fasta"
				]
			},
			{
				"tool_name": "HIVE-hexagon",
				"tool_desc": "Aligns reads to the reference",
				"tool_version": "1.4.3",
				"tool_package": "HIVE",
				"step_number": "4",
				"input_uri_list": [
					"https://hive/data/MAFFT/557008.fasta"
				],
				"output_uri_list": [
					"https://hive/data/hexagon/557009/allcounts-aligned.csv"
				]
			},
			{
				"tool_name": "HIVE-popolation_analysis",
				"tool_desc": "clone discovery tool",
				"tool_version": "1.4.3",
				"tool_package": "HIVE",
				"step_number": "5",
				"input_uri_list": [
					"https://hive/data/hexagon/557009/allcounts-aligned.csv"
				],
				"output_uri_list": [
					"https://hive/data/557010/popContig.fasta"
				]
			}
		]
	},
	"execution_domain": {
		"script": "hive://workflows/quasispecies_analysis_of_HIV-1_viruses_hive.py",
		"pipeline_version": "1.0",
		"platform": "HIVE",
		"driver": "//hive.biochemistry.gwu.edu/hive-driver",
		"software_prerequisites": [
			{
				"name": "HIVE-hexagon",
				"version": "1.4.3"
			},
			{
				"name": "HIVE-seq",
				"version": "1.4.3"
			},
			{
				"name": "HIVE-MAFFT",
				"version": "1.4.3"
			},
			{
				"name": "HIVE-hexagon",
				"version": "1.4.3"
			},
			{
				"name": "HIVE-population analysis",
				"version": "1.4.3"
			}
		],
		"domain_prerequisites": [
			{
				"url": "http://eutils.ncbi.nlm.nih.gov/entrez/eutils/",
				"name": "access to e-utils"
			},
			{
				"url": "ftp://:22/",
				"name": "access to ftp"
			}
		],
		"env_parameters": [
			"HIVEv1.4.3"
		],
		"script_type": "URI"
	},
	"parametric_domain": {
		"hexagon_seed": "0.01"
	},
	"io_domain": {
		"reference_uri_list": [
			"hive://genomes/333333"
		],
		"input_uri_list": [
			"hive://nuc-read/111111",
			"hive://nuc-read/222222",
			"hive://genomes/333333"
		],
		"output_uri_list": [
			"hive://data/888888/popContig ",
			"hive://data/888888/popAlignment ",
			"hive://data/888888/popCoverage ",
			"hive://data/888888/popBreakpoints ",
			"hive://data/888888/popSummary"
		]
	}
}
